# Android SDK setup (Windows)

Run once after installing Android Studio / SDK. SDK on this machine: `D:\AndroidStudio`.

```powershell
$androidHome = 'D:\AndroidStudio'

[Environment]::SetEnvironmentVariable('ANDROID_HOME', $androidHome, 'User')
[Environment]::SetEnvironmentVariable('ANDROID_SDK_ROOT', $androidHome, 'User')

$userPath = [Environment]::GetEnvironmentVariable('Path', 'User')
foreach ($p in @("$androidHome\platform-tools", "$androidHome\emulator")) {
  if ($userPath -notlike "*$p*") {
    $userPath = if ($userPath) { "$userPath;$p" } else { $p }
  }
}
[Environment]::SetEnvironmentVariable('Path', $userPath, 'User')

# Android Gradle Plugin requires JDK 17 (JDK 25 breaks native CMake builds).
$jdk17Candidates = @(
  'C:\Program Files\Microsoft\jdk-17.0.19.10-hotspot',
  'C:\Program Files\Java\jdk-17',
  'C:\Program Files\Eclipse Adoptium\jdk-17*'
)
$jdk17 = $jdk17Candidates | Where-Object { Test-Path "$_\bin\java.exe" } | Select-Object -First 1
if (-not $jdk17) {
  $jdk17 = (Get-ChildItem 'C:\Program Files\Microsoft' -Filter 'jdk-17*' -Directory -ErrorAction SilentlyContinue | Select-Object -First 1).FullName
}
if ($jdk17 -and (Test-Path "$jdk17\bin\java.exe")) {
  [Environment]::SetEnvironmentVariable('JAVA_HOME', $jdk17, 'User')
  Write-Host "JAVA_HOME set to JDK 17: $jdk17"

  $gradleDir = Join-Path $env:USERPROFILE '.gradle'
  New-Item -ItemType Directory -Force -Path $gradleDir | Out-Null
  $gradleProps = Join-Path $gradleDir 'gradle.properties'
  $javaHomeLine = "org.gradle.java.home=$($jdk17 -replace '\\','/')"
  if (Test-Path $gradleProps) {
    $existing = Get-Content $gradleProps -Raw
    if ($existing -match 'org\.gradle\.java\.home=') {
      $existing = $existing -replace 'org\.gradle\.java\.home=.*', $javaHomeLine
      Set-Content -Path $gradleProps -Value $existing.TrimEnd()
    } else {
      Add-Content -Path $gradleProps -Value $javaHomeLine
    }
  } else {
    Set-Content -Path $gradleProps -Value $javaHomeLine
  }
} else {
  Write-Host "JDK 17 not found. Install: winget install Microsoft.OpenJDK.17"
}

Write-Host "ANDROID_HOME = $androidHome"
Write-Host "Restart PowerShell / Cursor terminal, then run: adb devices"
```

After restarting the terminal:

```powershell
adb devices
cd "d:\GitHub Projects\CGSApple\remote-ar"
npx expo run:android
```

`remote-ar/android/local.properties` is generated by prebuild with `sdk.dir` for Gradle. If you move the SDK, delete `android/` and run `npx expo prebuild` again, or edit `local.properties`.
